require: rubocop-rails

Metrics/MethodLength:
  Enabled: false

Metrics/LineLength:
  Max: 120

Naming/AccessorMethodName:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false
